services:
  postgresql:
    container_name: postgresql-lbn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: library_book_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - lbn-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-lbn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lbn.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - lbn-network
    depends_on:
      - postgresql
    restart: unless-stopped

  keycloak:
    container_name: keycloak-lbn
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - 9000:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_ADMIN: localhost
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: library_book_network
      KC_DB_URL_HOST: postgresql-lbn
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password123
    depends_on:
      - postgresql
    networks:
      - lbn-network
    command:
      - "start-dev"

networks:
  lbn-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local